version: '3.7'

services:
  currency-exchange-service:
    image: mohsin/ms-springboot-currency-exchange-service:0.0.1-SNAPSHOT
    mem_reservation: 700m
    ports:
      - "8000:8000"
    networks:
      - currency-network
    depends_on:
      - naming-server
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://naming-server:8761/eureka
      MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: http://zipkin-server:9411/api/v2/spans

  currency-conversion-service:
    image: mohsin/ms-springboot-currency-conversion-service:0.0.1-SNAPSHOT
    mem_reservation: 700m
    ports:
      - "8100:8100"
    networks:
      - currency-network
    depends_on:
      - naming-server
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://naming-server:8761/eureka
      MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: http://zipkin-server:9411/api/v2/spans

  api-gateway:
    image: mohsin/ms-springboot-api-gateway:0.0.1-SNAPSHOT
    mem_reservation: 700m
    ports:
      - "8765:8765"
    networks:
      - currency-network
    depends_on:
      - naming-server
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://naming-server:8761/eureka
      MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: http://zipkin-server:9411/api/v2/spans

  naming-server:
    image: mohsin/ms-springboot-naming-server:0.0.1-SNAPSHOT
    mem_reservation: 700m
    ports:
      - "8761:8761"
    networks:
      - currency-network

  zipkin-server:
    image: openzipkin/zipkin:3.4.0
    mem_reservation: 300m
    ports:
      - "9411:9411"
    networks:
      - currency-network
    restart: always # Restart if there is a problem starting up

networks:
  currency-network: